/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/demo/document/unocss': RouteRecordInfo<'/demo/document/unocss', '/demo/document/unocss', Record<never, never>, Record<never, never>>,
    '/demo/document/vite': RouteRecordInfo<'/demo/document/vite', '/demo/document/vite', Record<never, never>, Record<never, never>>,
    '/demo/document/vue': RouteRecordInfo<'/demo/document/vue', '/demo/document/vue', Record<never, never>, Record<never, never>>,
    '/demo/document/vueuse': RouteRecordInfo<'/demo/document/vueuse', '/demo/document/vueuse', Record<never, never>, Record<never, never>>,
  }
}
